"""Provider-neutral message and tool types.

This is the ONLY vocabulary the agent, the tools and the eval ever see. Each provider
adapter translates to/from its own wire format (Anthropic content blocks, OpenAI
`tool_calls`). If you find yourself writing `if provider == "anthropic"` outside
`llm/`, the abstraction has leaked.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass(frozen=True)
class ToolSpec:
    """What the model sees: name + description + JSON Schema of the arguments.

    The model never sees code or URLs. This 'business card' is the whole contract,
    which is why the description is prompt engineering, not documentation.
    """
    name: str
    description: str
    parameters: dict[str, Any]  # JSON Schema, type=object


@dataclass(frozen=True)
class ToolCall:
    """A request emitted by the model: 'please run this tool with these arguments'.

    Nothing has been executed yet. `arguments` is untrusted input generated by a
    language model and must be validated before anything touches TerraOps.
    """
    id: str
    name: str
    arguments: dict[str, Any]


@dataclass
class UserMessage:
    text: str
    role: Literal["user"] = "user"


@dataclass
class AssistantMessage:
    text: str | None
    tool_calls: list[ToolCall] = field(default_factory=list)
    role: Literal["assistant"] = "assistant"


@dataclass
class ToolResultMessage:
    """The observation fed back to the model after OUR code executed a tool."""
    call_id: str
    name: str
    content: str            # JSON text; keep it small, the model reads it as tokens
    is_error: bool = False
    role: Literal["tool"] = "tool"


Message = UserMessage | AssistantMessage | ToolResultMessage


@dataclass
class LLMReply:
    """One model turn, normalised. Either text, tool calls, or both."""
    text: str | None
    tool_calls: list[ToolCall]
    stop_reason: str            # provider's raw reason, for logging only
    usage: dict[str, int] = field(default_factory=dict)

    @property
    def wants_tools(self) -> bool:
        return bool(self.tool_calls)
